
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: klm-backend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: klm-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klm-demo-deployment-backend
  labels:
    app: klm-demo
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: klm-backend
  template:
    metadata:
      labels:
        app: klm-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/jociky/klm-backend:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 3
        startupProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 0
          periodSeconds: 1

      imagePullSecrets:
      - name: ghcr-secret

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: klm-demo-deployment-frontend
  labels:
    app: klm-demo
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: klm-frontend
  template:
    metadata:
      labels:
        app: klm-frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/jociky/klm-frontend:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: ghcr-secret