name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# TODO: Both jobs do the same, use a template for this
jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Build the project
        working-directory: ./frontend
        run: npm run build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: ./frontend
        run: docker build -t ghcr.io/${{ github.repository }}-frontend:${{ github.sha }} .

      - name: Push Docker image
        working-directory: ./frontend
        run: docker push ghcr.io/${{ github.repository }}-frontend:${{ github.sha }}

      - name: Tag the Docker image with the latest tag
        run: |
          docker tag ghcr.io/${{ github.repository }}-frontend:${{ github.sha }} ghcr.io/${{ github.repository }}-frontend:latest
          docker push ghcr.io/${{ github.repository }}-frontend:latest

  build-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./backend
        run: npm ci

      - name: Build the project
        working-directory: ./backend
        run: npm run build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        working-directory: ./backend
        run: docker build -t ghcr.io/${{ github.repository }}-backend:${{ github.sha }} .

      - name: Push Docker image
        working-directory: ./backend
        run: docker push ghcr.io/${{ github.repository }}-backend:${{ github.sha }}

      - name: Tag the Docker image with the latest tag
        run: |
          docker tag ghcr.io/${{ github.repository }}-backend:${{ github.sha }} ghcr.io/${{ github.repository }}-backend:latest
          docker push ghcr.io/${{ github.repository }}-backend:latest